# Generated by Django 5.0 on 2023-12-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
