# Generated by Django 4.1.2 on 2023-12-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciept',
            name='final_price',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='finish_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
