# Generated by Django 5.0 on 2024-01-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parking",
            old_name="max_parking_spaces",
            new_name="max_parking_lots",
        ),
        migrations.RenameField(
            model_name="parking",
            old_name="occupied_places",
            new_name="occupied_lots",
        ),
        migrations.RenameField(
            model_name="parking",
            old_name="price_per_minute",
            new_name="price_per_hour",
        ),
        migrations.RemoveField(
            model_name="user",
            name="card_cvv",
        ),
        migrations.RemoveField(
            model_name="user",
            name="card_period",
        ),
        migrations.RemoveField(
            model_name="user",
            name="rights",
        ),
        migrations.AddField(
            model_name="user",
            name="barrier_control",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="car_num",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AddField(
            model_name="user",
            name="coupon_control",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="parking_control",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.IntegerField(default=-1, max_length=12),
        ),
        migrations.AddField(
            model_name="user",
            name="user_control",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="card_num",
            field=models.PositiveBigIntegerField(default=1111),
        ),
    ]
