# Generated by Django 5.0 on 2023-12-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_reciept_final_price_alter_reciept_finish_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='lattitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parking',
            name='longitude',
            field=models.IntegerField(default=0),
        ),
    ]
