# Generated by Django 5.0 on 2023-12-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_user_password2_alter_user_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
