# Generated by Django 5.0 on 2024-01-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "parkingapp",
            "0002_rename_max_parking_spaces_parking_max_parking_lots_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciept",
            name="parking_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reciept",
            name="user_id",
            field=models.IntegerField(default=0),
        ),
    ]
