# Generated by Django 5.0 on 2024-01-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0003_alter_reciept_parking_id_alter_reciept_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_view",
            field=models.BooleanField(default=False),
        ),
    ]
