# Generated by Django 4.1.2 on 2023-12-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0004_alter_parking_lattitude_alter_parking_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='free_time',
        ),
    ]
