# Generated by Django 4.1.2 on 2024-01-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0004_user_admin_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(default=-1),
        ),
    ]
