# Generated by Django 5.0 on 2024-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0005_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciept",
            name="price_per_hour",
            field=models.IntegerField(default=-1),
        ),
    ]
