# Generated by Django 5.0 on 2023-12-26 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0005_parking_last_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='last_changed',
            new_name='change',
        ),
    ]
