# Generated by Django 5.0 on 2024-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0006_reciept_price_per_hour"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciept",
            name="final_start_time",
            field=models.DateTimeField(default=None),
        ),
    ]
