# Generated by Django 5.0 on 2024-01-26 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0011_alter_reciept_final_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reciept",
            name="final_start_time",
            field=models.DateTimeField(
                default=datetime.datetime(1, 1, 1, 1, 0, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
