# Generated by Django 5.0 on 2024-01-26 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0012_alter_reciept_final_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="change",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1, 12, 31, 22, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reciept",
            name="final_start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1, 12, 31, 22, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reciept",
            name="finish_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1, 12, 31, 22, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reciept",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    1, 12, 31, 22, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
