# Generated by Django 5.0 on 2024-01-26 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "parkingapp",
            "0013_alter_parking_change_alter_reciept_final_start_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="change",
            field=models.DateTimeField(default=datetime.datetime(2, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="reciept",
            name="final_start_time",
            field=models.DateTimeField(default=datetime.datetime(2, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="reciept",
            name="finish_time",
            field=models.DateTimeField(default=datetime.datetime(2, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="reciept",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2, 1, 1, 0, 0)),
        ),
    ]
