# Generated by Django 5.0 on 2024-01-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "parkingapp",
            "0014_alter_parking_change_alter_reciept_final_start_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reciept",
            name="couponer_id",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="user",
            name="session_control",
            field=models.IntegerField(default=False),
        ),
    ]
