# Generated by Django 5.0 on 2024-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0015_reciept_couponer_id_user_session_control"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reciept",
            name="couponer_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="session_control",
        ),
        migrations.AddField(
            model_name="parking",
            name="code",
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=" ", max_length=16),
        ),
    ]
