# Generated by Django 5.0 on 2024-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0017_parking_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="parking_lot_view",
            field=models.BooleanField(default=False),
        ),
    ]
