# Generated by Django 5.0 on 2024-01-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0020_remove_parking_registry_nubmer"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciept",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
