# Generated by Django 5.0 on 2024-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0021_reciept_active_user_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reciept",
            name="active",
        ),
        migrations.AddField(
            model_name="parking",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
