# Generated by Django 5.0 on 2024-01-30 18:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0022_remove_reciept_active_parking_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parking",
            name="active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="active",
        ),
    ]
