# Generated by Django 5.0 on 2024-02-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0023_remove_parking_active_remove_user_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="car_num",
            field=models.CharField(default="", max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="card_num",
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=" ", max_length=16, unique=True),
        ),
    ]
