# Generated by Django 5.0 on 2024-02-16 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parkingapp", "0024_alter_user_car_num_alter_user_card_num_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password1",
        ),
        migrations.RemoveField(
            model_name="user",
            name="password2",
        ),
    ]
