# Generated by Django 4.1.2 on 2024-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0026_parking_reg_num_alter_user_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='reg_num',
            field=models.CharField(default='', max_length=100),
        ),
    ]
