# Generated by Django 4.1.2 on 2024-02-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0027_alter_parking_reg_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='parking_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
