# Generated by Django 4.1.2 on 2024-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0028_alter_reciept_parking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='park_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
